{
 "title": "RPC Overview",
 "tags": [ "RPC" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(eth_block_number,rpc_chain)"
    }
   },
   {
    "name": "rpc",
    "query": {
     "query": "label_values(eth_block_number{rpc_chain=\"$chain\"},rpc_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current age of last block",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - eth_block_timestamp{rpc_chain=~\"$chain\"})\n\n",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Age of last block",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - eth_block_timestamp{rpc_chain=~\"$chain\"}",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  { "title": "$chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "chain" },
  {
   "title": "Block Height ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_block_number{rpc_chain=\"$chain\"}",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Age of last block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - eth_block_timestamp{rpc_chain=\"$chain\"}",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Average block time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - eth_block_timestamp{rpc_chain=\"$chain\"}",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  }
 ]
}